services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - fin-analyze-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fin_analyzer
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 5s
      retries: 3

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: final
    ports:
      - 80:8080

  frontend:
    depends_on: 
      - backend
    build:
      context: "../frontend"
      dockerfile: Dockerfile
      target: final

volumes:
  fin-analyze-data: